### ISSUE TITLE
WifiControl.scanForWifi is not a function - typeError

### ISSUE THREAD

**Issue by shekit** [msolters/wifi-control-node#13]
Hi,

I keep getting this error while using the module on Mac OSX el capitan. I'm building an electron app and my code looks like this:

`var wifi = require('wifi-control');

```
wifi.init({
    debug: true
});

function scanWifi(){
    wifi.scanForWifi(function(err, resp){
        if(err){
            console.log("ERROR: "+ err)
        } else {
            console.log(resp)
        }
    })
}`
```

I can see the verbose debug output so I know the module has loaded correctly. However all the function calls in the module return this error.

I've tried this in a separate node app as well and this is the output of my console:

`WiFiControl: Debug mode set to: true
WiFiControl: Determining system wireless interface...
WiFiControl: Host machine is MacOS.
WiFiControl: Executing: networksetup -listallhardwareports | awk '/^Hardware Port: (Wi-Fi|AirPort)$/{getline;print $2}'
WiFiControl: Automatically located wireless interface en1.
/Users/abhishek/Google Drive/startups/thesis/code/server/app.js:56
wifi.scanForWifi(function(e,r){
     ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/abhishek/Google Drive/startups/thesis/code/server/app.js:56:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
[nodemon] app crashed - waiting for file changes before starting...`

Lastly if I console.log the wifi object I get this:

`{ init: [Function],
  configure: [Function],
  findInterface: [Function],
  scanForWiFi: [Function],
  connectToAP: [Function],
  resetWiFi: [Function],
  getIfaceState: [Function] }`

Out of these, if I console.log init, configure, findInterface and getIfaceState then it correctly logs the output.

However if I console.log scanForWifi, connectToAP or resetWifi, then it outputs `undefined` to the console.

**Comment by msolters** [comment]
Well, you're getting `undefined` from those 3 functions due to the fact that they are asynchronous functions.  They do not return anything.  Consider this section in the readme: https://github.com/msolters/wifi-control-node#synchronous.  Do you see the pattern?

That being said, it's hard for me to say exactly what error you're running into with your other messages but it certainly looks like a closure issue.  `Object.anonymous` is, I'm guessing, your `scanWiFi` wrapper function.  It's true that `undefined` is the value returned by the asynchronous function `scanForWiFi`.  But it doesn't look like you're executing the _return value of the function_ here, you're executing the function.

Therefore, the `undefined` error is probably due to the fact that, whatever context you're calling your `scanWiFi` wrapper function from, the `wifi` object is undefined, and hence any children are undefined.  That's my guess based on what I see here.  I'd begin debugging by adding `console.log(wifi)` _at the beginning of `scanWiFi`_.  See if `wifi` is defined at the time the function is called!

**Comment by msolters** [comment]
Either way, I will be closing this issue as it is not really an error intrinsic to this NPM package.  But if you're still stubbing your toe on this I'd be glad to provide my feedback to any source you can share.
